version: '3.8'
services:
  postgres-leader:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-leader-data:/var/lib/postgresql/data
      - ./init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh

  postgres-follower1:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-follower1-data:/var/lib/postgresql/data
    depends_on:
      - postgres-leader
    command: ["-c", "wal_level=replica", "-c", "hot_standby=on"]

  postgres-follower2:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-follower2-data:/var/lib/postgresql/data
    depends_on:
      - postgres-leader
    command: ["-c", "wal_level=replica", "-c", "hot_standby=on"]

volumes:
  postgres-leader-data:
  postgres-follower1-data:
  postgres-follower2-data: